### ISSUE TITLE
Version for Kibana v7.12.x

### ISSUE THREAD

**Issue by langustav** [synapticielfactory/kibana_cohort#3]
Hi,
firstly thanks for this code! Seems really cool. But I am currently running Kibana on version 7.3.1. and it is kind of difficult to upgrade for a newer version for now. Thus I have tried to build this plugin for 7.3.1., everything goes fine. However, after installation I can not see the plugin on status pages nor in visualization. 
Could you please provide a manual for building and releasing? Or it is not possible to built it for 7.3.1.?
Thank you!
Michal

**Comment by ylasri** [comment]
Will refer to this [PR](https://github.com/elastic/kibana/pull/88317) and release a new version for Kibana v7.12.x

**Comment by ylasri** [comment]
Hi @langustav if you have any chance to try the new changes for Kibana 7.12.0 and let us know if there is any issue so we can fix it
